spring:
  dbhandlers:
    mysql:
      connection:
        string: jdbc:mysql://localhost:3306
        dbname: AnalyticsProd
        username: root
        password:
      feedbacktablename: AnalyticsFeedback
      querylogstablename:
  mail:
      host: smtp.gmail.com
      port: 587
      username: phenomics.info@gmail.com
      password: Phenomics@1Notification
      properties:
        mail:
          smtp:
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000
            auth: true
            #send partial means that even if you have sent a list of email addresses where some are invalid, the mail will still be sent to the valid email addresses.
            sendpartial: true
            starttls:
              enable: true


emailConfig:
  fromAddress: phenomics.info@gmail.com
  retryCount: 2

logging:
  path: ./logs/
  file: ./logs/phenomics-notification.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %p | source= %c{1.} | %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %p | stackName=phenomics | appName=notification | source= %c{1.} | %msg%n"
  level:
    root: WARN
    au.org.garvan.kccg.notifications: INFO

server:
    port: 9090
